# Generated by Django 4.2.2 on 2023-06-07 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infobot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
